version: '2'
services:
  pmooos-app:
    image: pmooos
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://pmooos-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=PMOooS
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://pmooos-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://pmooos-elasticsearch:9200
  pmooos-mongodb:
    extends:
      file: mongodb.yml
      service: pmooos-mongodb
  pmooos-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: pmooos-elasticsearch
